name: prova_senai
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+2
  dio: ^4.0.0
  json_annotation: ^4.8.1
  

dev_dependencies:
  sqflite: ^2.0.0
  path: 1.8.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/question.json
